load 'deploy' if respond_to?(:namespace) # cap2 differentiator
Dir['vendor/plugins/*/recipes/*.rb'].each { |plugin| load(plugin) }

load 'config/deploy'

namespace :deploy do
  
  desc <<-DESC
  Start Thin processes on the app server.
  This uses the rackup command and the config.ru file
  DESC
  task :start , :roles => :app do
    run "/usr/bin/thin -C #{current_path}/config/thin_config.yaml start"
  end
  
  desc <<-DESC
  Stop the Thin process on the app server. 
  DESC
  task :stop , :roles => :app do
    run "/usr/bin/thin -C #{current_path}/config/thin_config.yaml stop"
  end

  desc <<-DESC
  Restart the Mongrel process on the app server. 
  DESC
  task :restart , :roles => :app do
    run "/usr/bin/thin -C #{current_path}/config/thin_config.yaml restart"
  end

end

namespace :sass do
  
  desc 'Updates the stylesheets generated by Sass.'
  task :update, :roles => :app do 
    run "cd #{latest_release}; RAILS_ENV=#{rails_env} rake sass:update"
  end

  before 'deploy:restart', 'sass:update'
  
end
